services:
  frontend:
    image: frontend_image
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - election-network

networks:
  election-network:
    driver: bridge
