services:
  admin_frontend:
    image: admin_frontend_image
    container_name: admin_frontend
    expose:
      - '8081'
    networks:
      - backend_net
      - admin_net
    depends_on:
      - backend
