services:
  admin-frontend:
    image: admin_frontend_image
    container_name: admin-frontend
    expose:
      - '8081'
    ports:
      - '8081:8081'
    networks:
      - backend_net
      - admin_net
    depends_on:
      - backend
