services:
  keycloak_db:
    image: postgres:17
    container_name: keycloak_postgres_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - kc-db-data:/var/lib/postgresql/data
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${KC_DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak-test
    networks:
      - backend_net
    environment:
      KEYCLOAK_BOOTSTRAP_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_LOG: ${KC_LOG}
      KC_LOG_CONSOLE_COLOR: ${KC_LOG_CONSOLE_COLOR}

    command: start-dev
    ports:
      - 8090:8090 # Expose Keycloak on port 8080 for local development
    restart: unless-stopped
    depends_on:
      keycloak_db:
        condition: service_healthy

volumes:
  kc-db-data:
