services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    env_file:
      - .env
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    networks:
      - election-network

  ldap-admin-ui:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin-ui
    env_file:
      - .env.ui
    ports:
      - 6443:80
    depends_on:
      - ldap
    networks:
      - election-network

networks:
  election-network:
    external: true

volumes:
  ldap-data:
  ldap_config:
